### ISSUE TITLE
Remove cardano-node dependency on systemd

### ISSUE THREAD

**Issue by mark-stopka** [2nd-Layer/docker-hub-cardano-images#36]
Currently, when `cardano-node` is build for Linux target, `journald` dependency is inherited from [iohk-monitoring-framework](https://github.com/input-output-hk/iohk-monitoring-framework/issues/523). This is useless dependency in Docker deployment.

IOHK upstream must introduce Cabal flags to disable unnecessary features to reduce application footprint and attack surface.

**Comment by angerman** [comment]
See https://github.com/input-output-hk/cardano-node/pull/911

**Comment by mark-stopka** [comment]
@angerman, thank you!

**Comment by mark-stopka** [comment]
Issue still seems present after merge of https://github.com/input-output-hk/cardano-node/pull/911

See https://github.com/input-output-hk/cardano-node/issues/1200 for details.

**Comment by mark-stopka** [comment]
Fixed for 1.20.0 by backport of https://github.com/input-output-hk/cardano-node/pull/1775
