### ISSUE TITLE
Storage readable check in  dock-entrypoint.sh startup 

### ISSUE THREAD

**Issue by deshawes** [2nd-Layer/docker-hub-cardano-images#76]
Small issue with commit c48a3ff23ba5c50c6e7a41c67e2cdc860bd984fe

if [[ -f ${JORM_DB_DIR}blocks.sqlite ]]; then
      if [[ ! -w ${JORM_DB_DIR}blocks.sqlite ]]; then

should read  

if [[ -f ${JORM_DB_DIR}blocks.sqlite ]]; then
      if [[ ! -r ${JORM_DB_DIR}blocks.sqlite ]]; then

**Comment by mark-stopka** [comment]
Thank's I'll look into it when RC2 will be officially out and I will be making an image for that! I really appreciate the community input, hope we will have more of that in the future, don't be afraid to even submit feature requests if you're using these images!

**Comment by mark-stopka** [comment]
Fixed in ceeb8f3.
