### ISSUE TITLE
Echo flag invalidates cabal.project.local contents

### ISSUE THREAD

**Issue by deshawes** [2nd-Layer/docker-hub-cardano-images#77]
commit c113f00 of 1.14.0

In Dockerfile the flag in "RUN echo -e ..."   invalidates contents of cabal.project.local.  Dependency  libsodium is not included and build of cardano-node fails. 
RUN echo -e  "package cardano-crypto-praos\n  flags: -external-libsodium-vrf" > cabal.project.local
should read 
RUN echo "package cardano-crypto-praos\n  flags: -external-libsodium-vrf" > cabal.project.local

**Comment by mark-stopka** [comment]
Fixed for 1.14.1 by db33a5b.
