### ISSUE TITLE
Docs to running a Cardano Node in Docker

### ISSUE THREAD

**Issue by pascalandy** [2nd-Layer/docker-hub-cardano-images#90]
Hi,

I asked [here](https://github.com/cardano-foundation/testnets-cardano-org/issues/284) and I'm still looking for docs to run a Cardano Node in Docker. I know Docker very well and I run many things in prod using docker, compose and stacks :)

**Now**, **where do we find all the configs to set up** ?

- The obvious one would be WALLET_ADDRESS to get our payments. I'm sure there is more to know.
- server requirements about the CPU and RAM ?
- Any blog post about that?

Thank you

**Comment by mark-stopka** [comment]
Hi, there is no WALLET_ADDRESS to be set, you need to register a stake pool on-chain and operator rewards address is part of that certificate.

To answer your two other questions:
  - best 2 cores at least and 8 GB for a block producer node.
  - you [should start here](https://cardano.org/stake-pool-operation#set-up-stake-pool), there is no magic involved when running it in Dockerized environment apart from using like Docker Swarm DNS service discovery to discover block producer and relay nodes,... basic stuff...
